apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: devops-lab
data:
  Caddyfile: |
    :8081 {
      encode gzip

      handle /api/* {
        reverse_proxy backend:3000
      }

      handle {
        reverse_proxy frontend:5173
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: devops-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:2
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: caddy-config-volume
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: caddy-config-volume
          configMap:
            name: caddy-config
---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: devops-lab
spec:
  selector:
    app: caddy
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
